Repository haileyport/PaldoGames, pull requests merged in 2022-09, with the labels that each got.

#24 ❗️✔️HOTFIX: Prisma 세팅 파일 위치 경로 에러 수정
  package-lock.json
  src/pages/api/auth/[...nextauth].js
  yarn.lock
Labels: bug

#32 🚀 Merge: eunhye => develop
  .gitignore
  package-lock.json
  package.json
  prisma/schema.prisma
  public/user.png
  src/components/Games/BaseBall/Balls.js
  src/components/Games/BaseBall/BaseBallMain.js
  src/components/Games/BaseBall/BaseBallMain.style.js
  src/components/Games/BaseBall/CurrentBaseBall.js
  src/components/Games/BaseBall/GetNumber.js
  src/components/Games/GamesMain/GamesMain.js
  src/components/Games/GamesResult/GamesResult.js
  src/components/Games/GamesResult/GamesResult.style.js
  src/components/Games/TicTacToe/Cell.js
  src/components/Games/TicTacToe/GameResult.js
  src/components/Games/TicTacToe/TicTacToeMain/Tictactoe.js
  src/components/Games/TicTacToe/TicTacToeMain/Tictactoe.style.js
  src/components/Games/TicTacToe/Tictactoe.js
  src/components/index.js
  src/pages/api/auth/[...nextauth].js
  src/pages/api/community/index.js
  src/pages/api/game/[userId].js
  src/pages/api/game/index.js
  src/pages/api/user/email/[email].js
  src/pages/api/user/id/[id].js
  src/pages/api/user/index.js
  src/pages/games/baseball.js
  src/pages/games/result.js
  src/pages/test.js
  src/pages/test2.js
  src/states/dummydata.js
  src/states/gameInfo.js
  src/states/index.js
  src/states/user.js
  yarn.lock
Labels: finished

#36 🚀Merge: jongyeol => develop
  next.config.js
  package-lock.json
  prisma/schema.prisma
  src/components/@commons/P/P.js
  src/components/Community/PageMain/MainHeader/MainHeader.js
  src/components/Community/Pagination/Pagination.js
  src/components/Community/Pagination/Pagination.style.js
  src/components/Community/Ranking/Ranking.style.js
  src/components/Community/Ranking/RankingMain.js
  src/components/Community/Ranking/crown.png
  src/components/Games/BaseBall/CurrentBaseBall.js
  src/components/Games/GamesCard/GamesCard.js
  src/components/Games/Lotto/Button/ButtonStart.js
  src/components/Games/Lotto/Button/ButtonStart.style.js
  src/components/Games/Lotto/Coupon/Coupon.js
  src/components/Games/Lotto/Coupon/Coupon.style.js
  src/components/Games/Lotto/Coupon/Field.js
  src/components/Games/Lotto/Coupon/Field.style.js
  src/components/Games/Lotto/Lotto.style.js
  src/components/Games/Lotto/LottoHeader/LottoHeader.js
  src/components/Games/Lotto/LottoHeader/LottoHeader.style.js
  src/components/Games/Lotto/LottoMain.js
  src/components/Games/Lotto/Result/Result.js
  src/components/Games/Lotto/Result/Result.style.js
  src/components/Games/WordRelay/CurrentGame.js
  src/components/Games/WordRelay/ErrorMessage.js
  src/components/Home/Footer/Footer.style.js
  src/components/Home/Header/Header.js
  src/components/Home/Header/NavProfile.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.style.js
  src/components/Modal/ModalFooter/ModalFooter.js
  src/components/Modal/ModalFooter/ModalFooter.style.js
  src/components/Modal/ModalHeader/ModalHeader.style.js
  src/components/Modal/ModalMain/CommunityModalMain.js
  src/components/Modal/ModalMain/ModalMain.js
  src/components/Modal/ModalMain/ModalMain.style.js
  src/components/Modal/ModalProfile/ModalProfile.js
  src/components/index.js
  src/pages/_app.js
  src/pages/community.js
  src/pages/games/Balls.js
  src/pages/games/baseball.js
  src/pages/games/index.js
  src/pages/games/lotto.js
  src/pages/games/wordrelay.js
  src/pages/index.js
  src/pages/inventories.js
  src/pages/ranking.js
  src/pages/test.js
  src/states/dummydata.js
  src/states/modal.js
  yarn.lock
Labels: finished

#42 ✒️Feat: 2048 게임 추가
  package-lock.json
  package.json
  prisma/schema.prisma
  src/components/Games/BaseBall/BaseBallMain.js
  src/components/Games/BaseBall/BaseBallMain.style.js
  src/components/Games/BaseBall/CurrentBaseBall.js
  src/components/Games/GamesMain/GamesMain.js
  src/components/Games/GamesResult/GamesResult.js
  src/components/Games/GamesResult/GamesResult.style.js
  src/components/Games/Merge/Cell.js
  src/components/Games/Merge/GameBoard.js
  src/components/Games/Merge/GameBoard.style.js
  src/components/Games/Merge/GameModal.js
  src/components/Games/Merge/GridContainer.js
  src/components/Games/Merge/Header/MergeHeader.js
  src/components/Games/Merge/MergeGameMain.js
  src/components/Games/Merge/MergeGameMain.style.js
  src/components/Games/Merge/TileContainer.js
  src/components/Games/WordRelay/CurrentGame.js
  src/components/Games/WordRelay/ErrorMessage.js
  src/components/Games/WordRelay/WordRelayMain/WordRelayMain.style.js
  src/components/index.js
  src/pages/api/auth/[...nextauth].js
  src/pages/api/game/[userId].js
  src/pages/api/game/index.js
  src/pages/api/user/email/[email].js
  src/pages/api/user/id/[id].js
  src/pages/api/user/index.js
  src/pages/games/Balls.js
  src/pages/games/baseball.js
  src/pages/games/index.js
  src/pages/games/merge.js
  src/pages/test.js
  src/pages/test2.js
  src/utils/merge/constants.js
  src/utils/merge/tile.js
  src/utils/merge/touchEvent.js
  yarn.lock
Labels: finished

#43 🚀Merge: keonhee => develop
  package-lock.json
  package.json
  public/loading.json
  src/components/@commons/Modal/ModalComponents/ModalComponents.style.js
  src/components/@commons/Modal/ModalComponents/ModalHeader.js
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/@commons/Modal/ModalMain/ProfileModalMain.js
  src/components/@commons/Modal/ModalProfile/ModalProfile.js
  src/components/@commons/Modal/ModalProfile/ModalProfile.style.js
  src/components/@commons/P/P.js
  src/components/Community/ContentModal/ContentModal.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentList.js
  src/components/Community/Pagination/Pagination.style.js
  src/components/Community/PostModal/PostModal.js
  src/components/Home/Footer/Footer.style.js
  src/components/Home/Header/Header.js
  src/components/Home/Header/NavLogin.js
  src/components/Home/Header/NavProfile.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.style.js
  src/components/Modal/ModalFooter/ModalFooter.js
  src/components/Modal/ModalFooter/ModalFooter.style.js
  src/components/Modal/ModalHeader/ModalHeader.style.js
  src/components/Modal/ModalMain/CommunityModalMain.js
  src/components/Modal/ModalMain/ModalMain.js
  src/components/Modal/ModalMain/ModalMain.style.js
  src/components/Modal/ModalProfile/ModalProfile.js
  src/components/index.js
  src/hooks/index.js
  src/hooks/useFetch.js
  src/hooks/usePatch.js
  src/pages/_app.js
  src/pages/community.js
  src/pages/games/baseball.js
  src/pages/games/index.js
  src/pages/games/wordrelay.js
  src/pages/index.js
  src/pages/login.js
  src/pages/ranking.js
  src/pages/test.js
  src/states/index.js
  src/styles/globals.css
  src/utils/utils.js
  yarn.lock
Labels: enhancement, finished

#52 🚀Merge: eunhye => develop
  README.md
  src/EasterEgg/FooterEasteregg.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/MainHeader/MainHeader.style.js
  src/components/Community/Ranking/Ranking.style.js
  src/components/Games/BaseBall/BaseBallMain.style.js
  src/components/Games/Merge/MergeGameMain.style.js
  src/components/Home/Footer/Footer.style.js
  src/pages/community.js
  src/pages/games/baseball.js
  src/pages/games/index.js
Labels: finished

#53 🚀Merge: Keonhee => develop
  prisma/schema.prisma
  server.js
  src/EasterEgg/FooterEasteregg.style.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PostModal/PostModal.js
  src/components/Community/Ranking/Ranking.style.js
  src/components/Games/BaseBall/BaseBallMain.style.js
  src/components/Home/Footer/Footer.style.js
  src/constants/index.js
  src/hooks/index.js
  src/hooks/useFetch.js
  src/hooks/usePatch.js
  src/pages/community.js
  src/pages/games/index.js
  src/pages/login.js
  yarn.lock
Labels: bug

#55 🚀Merge: keonhee => develop
  package-lock.json
  package.json
  prisma/schema.prisma
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/Games/BaseBall/CurrentBaseBall.js
  src/components/Games/TimesTables/TimesTablesMain.js
  src/components/Home/Footer/Footer.js
  src/pages/games/index.js
  yarn.lock
Labels: bug

#60 ❗️✔️HOTFIX: 게임 Table 생성 이슈 해결
  src/components/Community/PageMain/CommunityMain.js
  src/components/Games/BaseBall/BaseBallMain.style.js
  src/components/Home/Footer/Footer.style.js
  src/pages/games/index.js
  src/pages/index.js
Labels: bug

#66 🚀Merge: keonhee => develop
  package-lock.json
  package.json
  src/components/@commons/Modal/Modal.style.js
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PostModal/PostModal.js
  src/components/Home/Footer/Footer.js
  src/components/Home/Footer/Footer.style.js
  src/pages/index.js
  yarn.lock
Labels: bug, enhancement

#70 🚀Merge: develop => main
  package-lock.json
  package.json
  src/components/@commons/Modal/Modal.style.js
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PostModal/AdminPostModal.js
  src/components/Community/PostModal/PostModal.js
  src/components/Home/Header/NavProfile.js
  src/constants/index.js
  src/pages/_app.js
  src/pages/community.js
  src/pages/index.js
  yarn.lock
Labels: finished

#71 🛠Fix: 버튼 중복클릭 방지
  src/components/@commons/Modal/ModalMain/ProfileModalMain.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentList.js
  src/components/Community/PageMain/ContentList/ContentListProfile.js
  src/components/Community/PostModal/AdminPostModal.js
  src/components/Community/PostModal/PostModal.js
  src/components/Games/GamesMain/GamesMain.js
  src/components/Home/Header/Header.js
  src/components/Home/Header/NavProfile.js
  src/pages/community.js
  src/pages/index.js
Labels: bug

#73 🚀Merge: develop => keonhee
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentListProfile.js
  src/components/Home/Header/Header.js
Labels: bug

#76 🚀Merge: develop => main
  README.md
  package-lock.json
  package.json
  src/components/@commons/Modal/ModalMain/ProfileModalMain.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentList.js
  src/components/Community/PageMain/ContentList/ContentListProfile.js
  src/components/Community/PostModal/AdminPostModal.js
  src/components/Community/PostModal/PostModal.js
  src/components/Community/Ranking/RankingMain.js
  src/components/Games/GamesCard/GameButtons.js
  src/components/Games/GamesCard/GamesCard.js
  src/components/Games/GamesCard/GamesCard.style.js
  src/components/Games/GamesMain/GamesMain.js
  src/components/Home/Footer/EasterEgg/FooterEasterEgg.style.js
  src/components/Home/Header/Header.js
  src/components/Home/Header/NavProfile.js
  src/pages/_app.js
  src/pages/community.js
  src/pages/index.js
  yarn.lock
Labels: enhancement, finished

#77 ✒️Feat: 커뮤니티 custom hooks 적용
  src/components/@commons/Flex/Flex.js
  src/components/@commons/Flex/Flex.style.js
  src/components/@commons/Form/Form.style.js
  src/components/@commons/Input/Input.js
  src/components/@commons/Modal/Modal.js
  src/components/@commons/Modal/ModalComponents/ModalFooter.js
  src/components/@commons/Modal/ModalComponents/ModalHeader.js
  src/components/@commons/Modal/ModalMain/CardModalMain.js
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/@commons/Modal/ModalMain/ProfileModalMain.js
  src/components/@commons/index.js
  src/components/Community/ContentModal/ContentModal.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentList.js
  src/components/Community/PageMain/ContentList/ContentListProfile.js
  src/components/Community/PageMain/MainHeader/MainHeader.js
  src/components/Community/PostModal/AdminPostModal.js
  src/components/Community/PostModal/PostModal.js
  src/components/Community/Ranking/RankingMain.js
  src/components/Games/BaseBall/BaseBallMain.js
  src/components/Games/BaseBall/CurrentBaseBall.js
  src/components/Games/GamesCard/CardModal/CardModal.js
  src/components/Games/GamesCard/GameButtons.js
  src/components/Games/GamesCard/GamesCard.js
  src/components/Games/GamesCard/GamesCard.style.js
  src/components/Games/GamesMain/GamesMain.js
  src/components/Games/GamesMain/GamesMain.style.js
  src/components/Games/Lotto/LottoMain.js
  src/components/Games/Merge/GameBoard.js
  src/components/Games/Merge/Header/MergeHeader.js
  src/components/Games/TimesTables/TimesTablesMain.js
  src/components/Home/Footer/EasterEgg/FooterEasterEgg.js
  src/components/Home/Footer/Footer.js
  src/components/Home/Footer/Footer.style.js
  src/components/Home/Header/Header.js
  src/components/Home/Header/HomeLink/HomeLink.js
  src/components/Home/Header/NavProfile.js
  src/components/Home/Hero/Hero.js
  src/components/Home/Main/Animation.js
  src/components/Home/Main/Main.style.js
  src/hooks/apis/useAxios.js
  src/hooks/apis/useAxiosFunction.js
  src/hooks/apis/useAxiosInstance.js
  src/hooks/apis/useGet.js
  src/hooks/index.js
  src/hooks/useFetch.js
  src/pages/_document.js
  src/pages/community.js
  src/pages/games/baseball.js
  src/pages/games/index.js
  src/pages/index.js
  src/pages/login.js
  src/styles/globals.css
  yarn.lock
Labels: enhancement

#79 ✍️Design: 커뮤니티 메인 스타일 재정의
  .babelrc
  libs/client.js
  src/components/@commons/Modal/ModalComponents/ModalHeader.js
  src/components/@commons/Modal/ModalMain/CardModalMain.js
  src/components/@commons/Modal/ModalMain/CommunityModalMain.js
  src/components/@commons/Modal/ModalProfile/ModalProfile.js
  src/components/Community/ContentModal/ContentModal.js
  src/components/Community/EditModal/EditModal.js
  src/components/Community/PageMain/Community.style.js
  src/components/Community/PageMain/CommunityMain.js
  src/components/Community/PageMain/ContentList/ContentList.js
  src/components/Games/GamesCard/GamesCard.js
  src/components/Home/Footer/Footer.style.js
  src/components/Home/Header/NavLogin.js
  src/components/Home/Hero/Hero.js
  src/pages/api/restricted.js
  src/pages/community.js
  src/pages/easteregg.js
  src/pages/games/lotto.js
  src/pages/games/merge.js
  src/pages/ranking.js
  src/styles/globals.css
  src/utils/index.js
  src/utils/utils.js
Labels: enhancement
